language: rust
rust:
- stable
- beta
- nightly
script:
- | 
  ([ "$TRAVIS_RUST_VERSION" = "nightly" ] && cargo check -v --no-default-features) || [ "$TRAVIS_RUST_VERSION" != "nightly" ]
- cargo check -v
- cargo test -v
- cargo test --release -v
- |
  [ "$TRAVIS_RUST_VERSION" != "nightly" ] || cargo test --features const_generics -v
- |
  [ "$TRAVIS_RUST_VERSION" != "nightly" ] || cargo test --features const_generics --release -v
- cargo doc -v
