language: rust
rust:
- 1.20.0
- stable
- beta
- nightly
script:
- | 
  ([ "$TRAVIS_RUST_VERSION" = "nightly" ] && cargo check -v --no-default-features) || [ "$TRAVIS_RUST_VERSION" != "nightly" ]
- cargo check -v
- cargo test -v
- cargo test --release -v
- cargo doc -v
